CREATE EXTERNAL TABLE dbo.STAGING_RIDER
(
    [RIDER_ID] NVARCHAR(4000),
    [FIRSTNAME] NVARCHAR(4000),
    [LASTNAME] NVARCHAR(4000),
    [ADDRESS] NVARCHAR(4000),
    [BIRTHDAY] NVARCHAR(4000),
    [ACCOUNT_START_DATE] NVARCHAR(4000),
    [ACCOUNT_END_DATE] NVARCHAR(4000),
    [IS_MEMBER] NVARCHAR(10)
)

WITH (
    LOCATION = 'Source/public.rider.csv',
    DATA_SOURCE = [AZURESTORAGE],
    FILE_FORMAT = [TextFileFormat_WithHeader]
)

GO

SELECT TOP 10 * FROM DBO.STAGING_RIDER
GO