CREATE EXTERNAL TABLE dbo.STAGING_TRIP
(
    [TRIP_ID] NVARCHAR(4000),
    [RIDEABLE_TYPE] NVARCHAR(4000),
    [START_AT] VARCHAR(50),
    [ENDED_AT] VARCHAR(50),
    [START_STATION_ID] NVARCHAR(4000),
    [END_STATION_ID] NVARCHAR(4000),
    [RIDER_ID] BIGINT
)
WITH
(
    LOCATION = 'Source/public.trip.csv',
    DATA_SOURCE = [AZURESTORAGE],
    FILE_FORMAT = [TextFileFormat_WithHeader]
)

GO

SELECT TOP 100 * FROM DBO.STAGING_TRIP
GO