CREATE EXTERNAL TABLE dbo.STAGING_STATION
(
    [STATION_ID] NVARCHAR(4000),
    [NAME] NVARCHAR(4000),
    [LATITUDE] FLOAT,
    [LONGITUDE] FLOAT
)
WITH
(
    LOCATION = 'Source/public.station.csv',
    DATA_SOURCE = [AZURESTORAGE],
    FILE_FORMAT = [TextFileFormat_WithHeader]
)
GO

SELECT TOP 100 * FROM DBO.STAGING_STATION
GO