-- CREATE FACT_TRIP TABLE
IF OBJECT_ID('DBO.FACT_TRIP') IS NOT NULL BEGIN DROP EXTERNAL TABLE DBO.FACT_TRIP;

END CREATE EXTERNAL TABLE [DBO].[FACT_TRIP] WITH (
    LOCATION = 'Star_schema/FACT_TRIP',
    DATA_SOURCE = [AzureStorage],
    FILE_FORMAT = [TextFileFormat_WithHeader]
) AS
SELECT
    ST.TRIP_ID,
    ST.RIDER_ID,
    ST.START_AT,
    ST.ENDED_AT,
    ST.START_STATION_ID,
    ST.END_STATION_ID,
    ST.RIDEABLE_TYPE,
    DATEDIFF(HOUR, ST.START_AT, ST.ENDED_AT) AS DURATION,
    DATEDIFF(YEAR, SR.BIRTHDAY, ST.START_AT) AS RIDER_AGE
FROM
    STAGING_TRIP AS ST
    JOIN STAGING_RIDER SR ON SR.RIDER_ID = ST.RIDER_ID;

SELECT TOP 10 * FROM DBO.FACT_TRIP;