-- CREATE DIM_RIDER TABLE
IF OBJECT_ID('DBO.DIM_RIDER') IS NOT NULL BEGIN DROP EXTERNAL TABLE DBO.DIM_RIDER
    END CREATE EXTERNAL TABLE [DBO].[DIM_RIDER] WITH (
        LOCATION = 'Star_schema/DIM_RIDER',
        DATA_SOURCE = [AzureStorage],
        FILE_FORMAT = [TextFileFormat_WithHeader]
) AS
SELECT
    [RIDER_ID],
    [FIRSTNAME],
    [LASTNAME],
    [ADDRESS],
    [BIRTHDAY],
    [ACCOUNT_START_DATE],
    [ACCOUNT_END_DATE],
    [IS_MEMBER]
FROM
STAGING_RIDER;

GO
SELECT TOP 10 * FROM [DBO].[DIM_RIDER];