-- CREATE DIM_PAYMENT TABLE
IF OBJECT_ID('DBO.DIM_PAYMENT') IS NOT NULL BEGIN DROP EXTERNAL TABLE DBO.DIM_PAYMENT;

END CREATE EXTERNAL TABLE [DBO].[DIM_PAYMENT] WITH (
    LOCATION = 'Star_schema/DIM_PAYMENT',
    DATA_SOURCE = [AzureStorage],
    FILE_FORMAT = [TextFileFormat_WithHeader]
) AS (
    SELECT
        PAYMENT_ID,
        DATE,
        RIDER_ID,
        AMOUNT,
        DATEPART(DAY, CONVERT(DATE, DATE)) AS DAY,
        DATEPART(MONTH, CONVERT(DATE, DATE)) AS MONTH,
        DATEPART(QUARTER, CONVERT(DATE, DATE)) AS QUARTER,
        DATEPART(YEAR, CONVERT(DATE, DATE)) AS YEAR,
        DATEPART(DAYOFYEAR, CONVERT(DATE, DATE)) AS DAY_OF_YEAR,
        DATEPART(WEEKDAY, CONVERT(DATE, DATE)) AS DAY_OF_WEEK
    FROM
        dbo.STAGING_PAYMENT
);
GO
SELECT TOP 10 * FROM [DBO].[DIM_PAYMENT];