-- CREATE DIM_STATION TABLE
IF OBJECT_ID('DBO.DIM_STATION') IS NOT NULL BEGIN DROP EXTERNAL TABLE DBO.DIM_STATION;

END CREATE EXTERNAL TABLE [DBO].[DIM_STATION] WITH (
    LOCATION = 'Star_schema/DIM_STATION',
    DATA_SOURCE = [AzureStorage],
    FILE_FORMAT = [TextFileFormat_WithHeader]
) AS
SELECT
    [STATION_ID],
    [NAME],
    [LATITUDE],
    [LONGITUDE]
FROM
    STAGING_STATION;

SELECT TOP 10 * FROM DBO.DIM_STATION;